language: scala
jdk: openjdk8
sudo: false

before_install:
  - umask 0022
  - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.3.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -f -v 3.2.1

cache:
  directories:
   - $HOME/.scalding.dep.cache

script:
  - scripts/testValidator.sh

addons:
  apt:
    packages:
    - md5deep

matrix:
  include:
#BASE TESTS
    - scala: 2.12.14
      env: BUILD="test repl and typed tutorials"
      script:
      - "scripts/build_assembly_no_test.sh scalding-repl"
      - "scripts/test_repl_tutorial.sh"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7b7b19bebb32fb18c9c2
    on_success: change
    on_failure: always
    on_start: never
